version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: blog
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  db_volume:
